branch-defaults:
  default:
    environment: Pomeapi-env
global:
  application_name: pome_api
  default_ec2_keyname: null
  default_platform: node.js
  default_region: ap-northeast-1
  profile: null
  sc: git
  workspace_type: Application