version: 2.1

orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-and-deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup

# Installing the api dependencies
      - run:
          name: API Install
          command: |
            npm install
# Building the backend
      - run:
          name: Back-End Build
          command: |
            npm run build
# Installing AWS Elastic Beanstalk CLI
      - run:
          name: Installing AWS Elasticbeanstalk
          command: |
            npm run aws-eb
# Deploying the backend to AWS Elastic Beanstalk
      - run:
          name: Back-End Deploy
          command: |
            npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: aws
          filters:
            branches:
              only:
                - main